name: Discord Notification on Issue & Pull Request

on:
  issues:
    types: [opened, labeled] # ìƒˆë¡œìš´ ì´ìŠˆê°€ ìƒì„±ë˜ê±°ë‚˜ Labelì´ ì¶”ê°€ë  ë•Œ ìž‘ë™
  pull_request:
    types: [opened, reopened] # PRì´ ì—´ë ¸ì„ ë•Œ ìž‘ë™

jobs:
  notify-on-event:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "EVENT_TYPE=${{ github.event_name }}" >> $GITHUB_ENV
          echo "ISSUE_BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "ISSUE_LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')" >> $GITHUB_ENV
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.sender.login }}" >> $GITHUB_ENV
          echo "ISSUE_URL=${{ github.event.issue.html_url }}" >> $GITHUB_ENV
          echo "ISSUE_AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
          echo "WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Filter Events & Send Notification
        run: |
          JSON_FILE=$(mktemp)

          # íŠ¹ì • Labelì´ ìžˆëŠ” ê²½ìš°ë§Œ ì•Œë¦¼ ì „ì†¡
          if [[ "$EVENT_TYPE" == "issues" && "$ISSUE_LABELS" =~ "task-request" ]]; then
            cat > $JSON_FILE <<EOF
            {
              "content": "**ðŸ“¢ ìƒˆë¡œìš´ ìž‘ì—… ìš”ì²­ì´ ë“±ë¡ë˜ì—ˆìŠµë‹ˆë‹¤!**",
              "embeds": [
                {
                  "author": {
                    "name": "$ISSUE_AUTHOR",
                    "icon_url": "https://github.com/$ISSUE_AUTHOR.png"
                  },
                  "title": "ðŸ”— [GitHub ì´ìŠˆ ë§í¬]($ISSUE_URL)",
                  "description": "ì´ìŠˆ í…œí”Œë¦¿ì„ ê¸°ë°˜ìœ¼ë¡œ ìƒì„±ëœ ìš”ì²­ìž…ë‹ˆë‹¤.",
                  "color": 15258703,
                  "footer": {
                    "text": "GitHub Actions | Issue Alert"
                  },
                  "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
                }
              ]
            }
            EOF
            curl -X POST -H 'Content-type: application/json' --data @$JSON_FILE $WEBHOOK_URL
          fi

          rm $JSON_FILE
